# Generated by Django 2.2.5 on 2019-10-02 13:08

import commenting.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(default='')),
                ('domain', commenting.fields.DomainNameField(blank=True, max_length=72, null=True)),
                ('path', models.CharField(blank=True, max_length=1500)),
                ('score', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commenting.Comment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
