<<<<<<< HEAD
# Generated by Django 2.2.5 on 2019-10-02 13:08

import commenting.fields
=======
# Generated by Django 2.2.6 on 2019-10-11 16:12

>>>>>>> khan
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('management', '0001_initial'),
>>>>>>> khan
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=700)),
                ('locked', models.BooleanField(default=False)),
                ('site', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Site', verbose_name='Site')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(default='', verbose_name='Comment body')),
                ('score', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
<<<<<<< HEAD
                ('body', models.TextField(default='')),
                ('domain', commenting.fields.DomainNameField(blank=True, max_length=72, null=True)),
                ('path', models.CharField(blank=True, max_length=1500)),
                ('score', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
=======
                ('commenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('page', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='commenting.Page')),
>>>>>>> khan
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commenting.Comment')),
            ],
        ),
    ]
