# Generated by Django 2.2.6 on 2019-10-27 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='commenting.Page'),
        ),
    ]
