# Generated by Django 2.2.5 on 2019-09-26 19:59

import commenting.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commenting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='domain',
            field=commenting.fields.DomainField(blank=True, max_length=72, null=True),
        ),
    ]
