# Generated by Django 2.2.6 on 2019-10-27 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import management.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', management.fields.DomainNameField(max_length=72, unique=True, verbose_name='Domain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to=settings.AUTH_USER_MODEL, verbose_name='Site Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Moderation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderate_all', models.BooleanField(default=False, verbose_name='Require all comments to be approved manually')),
                ('moderate_anonymouse', models.BooleanField(default=True, verbose_name='Require anonymous comments to be approved manually')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='management.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_anonymouse', models.BooleanField(default=False, verbose_name='Anonymouse Comments')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='management.Site')),
            ],
        ),
    ]
