# Generated by Django 2.2.6 on 2019-11-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Moderation',
            new_name='ModerationSetting',
        ),
    ]
